export const apiContract = {
  signup: "/user/signup",
  login: "/user/login",
  checkLogin: "/user/logged",
  fetUserDetails: "/user/get-user-detail",
  addFriend: "/user/add-friend",
  getFriendList: "/user/get-friend-list",
  removeFriend: "/user/remove-friend",
  createNewGroup: "/user/group/create-group",
  getGroupList: "/user/group/get-list",
  editGroupdetails: "/user/group/edit-group",
  getGroupDetails: "/user/group/get-group-details",
  addNewTransaction: "/user/group/transactions/new-payment",
  getTransactionDetails: "/user/group/transactions/get-transaction-list",
  getTransactionAmount: "/user/group/transactions/get-count",
  uploadImage: "/s3/upload",
};
